In [15]:
#Problem Statement Scenario: Understanding Workforce & Business Challenges

#A company is facing multiple challenges across different domains:

#Employee Attrition: HR suspects that certain departments are losing employees faster than others, and they want to identify patterns.
#Sales Data: The sales team wants to understand which products and regions are performing best, and whether missing data is affecting their reporting.
#Telecom Churn: The telecom division is worried about losing customers and wants to explore churn-related factors.
#As a Data Scientist, you are tasked with conducting initial exploratory analysis on one of these datasets using Jupyter Notebook. Your goal is to provide quick insights that management can act upon

import pandas as pd
import numpy as np

In [ ]:
df.shape

(15, 9)

In [ ]:
df = pd.read_csv("employeeattrition.csv")

In [ ]:
df.head()

,Employee_ID,Age,Department,Job_Role,Monthly_Income,Years_at_Company,Overtime,Job_Satisfaction,Attrition
0,E001,29,Sales,Sales Executive,45000,3,Yes,4.0,No
1,E002,35,HR,HR Manager,52000,7,No,3.0,No
2,E003,28,IT,Software Engineer,60000,2,Yes,2.0,Yes
3,E004,42,Finance,Accountant,58000,10,No,4.0,No
4,E005,31,Sales,Sales Executive,47000,4,Yes,3.0,Yes

In [ ]:
df.shape

(15, 9)

In [ ]:
df.describe()

             Age  Monthly_Income  Years_at_Company  Job_Satisfaction
count  15.000000       15.000000         15.000000         14.000000
mean   32.733333    56533.333333          4.800000          3.285714
std     5.599320    11057.425861          2.908117          0.913874
min    24.000000    45000.000000          1.000000          2.000000
25%    28.500000    48500.000000          2.500000          3.000000
50%    32.000000    54000.000000          4.000000          3.000000
75%    37.000000    60000.000000          7.000000          4.000000
max    42.000000    85000.000000         10.000000          5.000000

In [ ]:
df.isnull().sum()

Employee_ID         0
Age                 0
Department          0
Job_Role            0
Monthly_Income      0
Years_at_Company    0
Overtime            0
Job_Satisfaction    1
Attrition           0
dtype: int64

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 9 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   Employee_ID       15 non-null     object
 1   Age               15 non-null     int64
 2   Department        15 non-null     object
 3   Job_Role          15 non-null     object
 4   Monthly_Income    15 non-null     int64
 5   Years_at_Company  15 non-null     int64
 6   Overtime          15 non-null     object
 7   Job_Satisfaction  14 non-null     float64
 8   Attrition         15 non-null     object
dtypes: float64(1), int64(3), object(5)
memory usage: 1.2+ KB

In [ ]:
df.columns

Index(['Employee_ID', 'Age', 'Department', 'Job_Role', 'Monthly_Income',
       'Years_at_Company', 'Overtime', 'Job_Satisfaction', 'Attrition'],
      dtype='object')

In [ ]:
df.tail()

,Employee_ID,Age,Department,Job_Role,Monthly_Income,Years_at_Company,Overtime,Job_Satisfaction,Attrition
10,E011,36,IT,Data Scientist,85000,5,No,5.0,No
11,E012,41,Sales,Sales Executive,49000,9,Yes,3.0,Yes
12,E013,24,IT,Software Engineer,54000,1,Yes,2.0,Yes
13,E014,38,Finance,Accountant,60000,7,No,4.0,No
14,E015,32,HR,HR Executive,47000,4,No,3.0,No

In [ ]:
df.dtypes

Employee_ID          object
Age                   int64
Department           object
Job_Role             object
Monthly_Income        int64
Years_at_Company      int64
Overtime             object
Job_Satisfaction    float64
Attrition            object
dtype: object